services: docker
git:
  depth: 1

jobs:
   include:
      - &test
        env:
          - MY_VAR=1
        script: docker run -it alpine sh -c 'cd /usr && ls && echo $MY_VAR > /proc/1/fd/1'
      - <<: *test
        name: 2
        env:
          - MY_VAR=2
      - <<: *test
        name: 3
        env:
          - MY_VAR=3




