language: python
services: docker
python:
  - "2.7"
git:
  depth: 1

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master

jobs:
   include:
      - build:
        script: echo "done"
      - &test
        env:
          - COUCHDB_USER=op   
          - COUCHDB_PASSWORD=op
          - MY_VAR=1
        script:
          - docker run -d --net=host couchdb:1.7.2 
          - docker run -it --add-host=couchdb:127.0.0.1 alpine sh -c 'cd /usr && ls && echo $MY_VAR > /proc/1/fd/1'
      - <<: *test
        name: 2
        env:
          - MY_VAR=2
      - <<: *test
        name: 3
        env:
          - MY_VAR=3
      - <<: *test
        name: 4
        env:
          - MY_VAR=4




