language: python
services: docker
python:
  - "2.7"
git:
  depth: 1

jobs:
   include:
      - &test
        env:
          - COUCHDB_USER=op   
          - COUCHDB_PASSWORD=op
        script: 
          - docker run -d --net=host couchdb:1.7.2 
          - docker run -it alpine sh -c 'cd /usr && ls && echo $MY_VAR > /proc/1/fd/1'
      - <<: *test
        name: 2
        env:
          - MY_VAR=2
      - <<: *test
        name: 3
        env:
          - MY_VAR=3
      - <<: *test
        name: 4
        env:
          - MY_VAR=4




