services: docker
git:
  depth: 1

jobs:
  include:
   - script: docker run -it alpint bash -c 'echo "1" > /proc/1/fd/1'
     name: 1
   - script: docker run -it alpint bash -c 'echo "2" > /proc/1/fd/1'
     name: 2
